### ISSUE TITLE
JQuery not working

### ISSUE THREAD

**Issue by PenetratingShot** [PenetratingShot/Snowflake#4]
The Jquery isn't compiling correctly. Lemme redo all of it

**Comment by talonbragg** [comment]
I WILL HELP YOU

**Comment by talonbragg** [comment]
:3

**Comment by talonbragg** [comment]
LOL :3 :3

**Comment by PenetratingShot** [comment]
I put cloudflare on dev mode

**Comment by talonbragg** [comment]
Hey go to google hangouts ok

**Comment by talonbragg** [comment]
This is almost fixed mainly just have to fix the background image now.

**Comment by talonbragg** [comment]
Looks like jquery is not compiling because it is linked in the `<head>` tag and not at the bottom of the `<body>` tag.

**Comment by talonbragg** [comment]
The Jquery now works! You just had to add a `document.ready(function() {});` to each jquery function.

**Comment by PenetratingShot** [comment]
Alright
