### ISSUE TITLE
New Bug (Inspect Element)

### ISSUE THREAD

**Issue by PenetratingShot** [PenetratingShot/Snowflake#6]
Uncaught ReferenceError: $ is not defined at main.js:1
Uncaught ReferenceError: $ is not defined at snowflake.js:1

**Comment by PenetratingShot** [comment]
Looks all good to me. I don't know what Google is cribbing about

**Comment by talonbragg** [comment]
Fixed it just needed this `<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>`.  👍 

**Comment by PenetratingShot** [comment]
Cool
